name: "HA-USBIP"
version: "0.1.4"
slug: "ha_usbip"
description: "Minimal USB/IP client add-on that attaches configured remote devices"
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
host_network: true
privileged: true
options:
  attachments:
    - "192.168.1.13 1-1.2"
schema:
  attachments:
    type: array
    items:
      type: string
