name: Bump version and set exec bits on push to main

on:
  push:
    branches:
      - main
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make in-repo scripts executable in workspace
        run: |
          chmod +x .github/scripts/bump-version.sh || true
          chmod +x .github/scripts/git-set-exec.sh || true
          chmod +x rootfs/usr/local/bin/simple-usbip-client.sh || true
          chmod +x rootfs/etc/cont-init.d/10-startup.sh || true
          chmod +x rootfs/etc/cont-init.d/create_devices.sh || true
          chmod +x rootfs/etc/services.d/usbip/run || true
          chmod +x rootfs/etc/services.d/usbip/finish || true

      - name: Ensure executable bits are set in git index and commit
        run: ./.github/scripts/git-set-exec.sh

      - name: Run bump script
        run: bash .github/scripts/bump-version.sh

      - name: Commit bump changes if any
        run: |
          git add config.yaml CHANGELOG.md || true
          if ! git diff --staged --quiet; then
            git commit -m "chore: bump version [skip ci]" || echo "nothing to commit"
            git push origin HEAD:main || git push origin HEAD:master || true
          else
            echo "No version change detected"
          fi
